bookit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from mainUI import views
from registration.backends.simple.views import RegistrationView

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mainUI/', include('mainUI.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    
]

mainUI/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'mainUI'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^success_stories/(?P<id>\d+)/$', views.success_stories, name='success_stories'),
    url(r'^register-provider$', views.register_provider, name='register_provider'),
    url(r'^register-customer$', views.register_customer, name='register_customer'),
    url(r'^srvgroups/',views.srvgroups, name='srvgroups'),
    url(r'^availablesrv/(?P<id>\d+)/$',views.availablesrv, name='availablesrv'),
    url(r'^srvproviders/(?P<id>\d+)/$',views.srvproviders, name='srvproviders'),
    url(r'^selectdate/(?P<id>\d+)/$', views.select_date, name='select_date'),
    url(r'^confirmation/(?P<id>\d+)/$', views.select_date, name='select_date'),
    url(r'^request_booking/$', views.request_booking, name='request_booking'),
    url(r'^request_sent/$', views.request_booking, name='request_sent'),
    url(r'^user_profile/$', views.user_profile, name='user_profile'),
    url(r'^pending_bookings/$', views.pending_bookings, name='pending_bookings'),
    url(r'^upcoming_bookings/$', views.upcoming_bookings, name='upcoming_bookings'),
    url(r'^confirm_booking/(?P<id>\d+)/$', views.confirm_booking, name='confirm_booking'),
    url(r'^decline_booking/(?P<id>\d+)/$', views.decline_booking, name='decline_booking'),
    url(r'^cancel_booking/(?P<id>\d+)/$', views.cancel_booking, name='cancel_booking'),

]

mainUI/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from phonenumber_field.modelfields import PhoneNumberField


# Working day: a day of the week with working hours
class WorkingDays(models.Model):
    working_day = models.IntegerField()  # 0-Monday to 6-Sunday
    working_day_description = models.CharField(max_length=30)  # the name of the day
    start_hour = models.TimeField()  # the opening hour
    end_hour = models.TimeField()  # the closing hour

    def __str__(self):
            return self.working_day_description + ' ' + str(self.start_hour)+' - ' + str(self.end_hour)

    class Meta:
        verbose_name_plural = 'Working Days Plans'


# Working Plan: is a group of working days that create 
class WorkingPlan(models.Model):
    working_plan_name = models.CharField(max_length=50)
    working_day = models.ManyToManyField(WorkingDays)

    def __str__(self):
            return self.working_plan_name

    class Meta:
        verbose_name = 'Working Hours'
        verbose_name_plural = 'Working Plans'


# ServiceProviders: a Model for service providers
class ServiceProviders(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    provider_businness_name = models.CharField(max_length=128)
    provider_address = models.CharField(max_length=30, verbose_name='Address')
    provider_zipcode = models.CharField(max_length=10, verbose_name='Zip Code')
    working_plan = models.ForeignKey(WorkingPlan, on_delete=models.CASCADE)

    def __str__(self):
            return self.provider_businness_name

    class Meta:
        verbose_name_plural = 'Service Providers'
                

# Category: a model for categorising services
class ServiceCategory(models.Model):
    category_name = models.CharField(max_length=60)

    def __str__(self):
            return self.category_name

    class Meta:
        verbose_name_plural = 'Service Categories'


# Services: a model for the services available
class Services(models.Model):
    service_name = models.CharField(max_length=30)
    
    service_category = models.ManyToManyField(ServiceCategory)
    service_commission = models.FloatField(validators=[MinValueValidator(0.5), MaxValueValidator(99)])

    def __str__(self):
            return self.service_name

    class Meta:
        verbose_name_plural = 'Services'


# Provider services: a Model for services of each provider
class ProviderService(models.Model):
    provider = models.ForeignKey(ServiceProviders, on_delete=models.CASCADE)
    service = models.ForeignKey(Services, on_delete=models.CASCADE)
    service_description = models.CharField(max_length=1000)    
    price = models.FloatField(validators=[MinValueValidator(0)])
    duration = models.IntegerField(validators=[MinValueValidator(0)])

    def __str__(self):
            return self.provider.provider_businness_name + ' => Service:' + self.service.service_name

    class Meta:
        verbose_name_plural = 'Provider Services'


# Customer: A Model for customers
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    customer_phone = PhoneNumberField()

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name_plural = 'Customers'
    

# Booking: A Model for bookings
class Booking(models.Model):
    booking_request_date = models.DateTimeField(default=datetime.now())  # the date & time the request was made
    booking_date = models.DateTimeField()  # the date & time the booking will be held
    booking_service = models.ForeignKey(Services, on_delete=models.CASCADE)
    booking_provider = models.ForeignKey(ServiceProviders, on_delete=models.CASCADE)
    booking_confirmed = models.BooleanField(default=False)
    booking_canceled = models.BooleanField(default=False)
    booking_excecuted = models.BooleanField(default=False)  # for future use
    booking_charged = models.BooleanField(default=False)  # for future use
    booking_customer = models.ForeignKey(Customer, on_delete=models.CASCADE)    
    
    def __str__(self):
                return self.booking_customer.user.first_name + ' provider: ' + \
                       self.booking_provider.provider_businness_name + ' => Service:' + \
                       self.booking_service.service_name
    
    class Meta:
        verbose_name_plural = 'Bookings'

mainUI/forms.py
from django import forms
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from django.contrib.auth.models import User
from mainUI.models import ServiceProviders, Customer, Booking


# Form class for django's User model
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 
        'first_name', 'last_name')


# Form class for ServiceProvider model
class ServiceProvidersForm(forms.ModelForm):
  
    class Meta:
        model = ServiceProviders
        exclude = ('user_type', 'user',)


# Form class for Customer model
class CustomerForm(forms.ModelForm):
    
    class Meta:
        model = Customer
        fields = ['customer_phone',]    
        widgets = {'customer_phone': PhoneNumberPrefixWidget()} 
        exclude = ('user_type', 'user',)


# Form class for allowing the user to pick a date
class DatePickForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ['booking_date']
        widgets = {'booking_date': forms.DateTimeInput(attrs={'class': 'datetime-input'})}

mainUI/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from mainUI.forms import UserForm, ServiceProvidersForm, CustomerForm, DatePickForm
from .models import ProviderService, ServiceCategory, Services, ServiceProviders,\
    WorkingPlan, WorkingDays, Booking, Customer
from django.urls import reverse
from django_tables2 import RequestConfig
from .tables import ServiceProvidersTable, WorkingPlansTable, ProviderPendingBookingsTable,\
    CustomerPendingBookingsTable, ProviderUpcomingBookingsTable, CustomerUpcomingBookingsTable
from .utility import validateBookingDay, read_email_pass
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from django.core.mail import BadHeaderError, send_mail
from django.db import connection

# View for the homepage
def index(request):
    
    return render(request, 'mainUI/index.html')


# View for the about page
def about(request):

    return render(request, 'mainUI/about.html')


def success_stories(request,id):
           
    return render(request, 'mainUI/success_stories.html', {'id': id})



# View that allows new service providers to register
def register_provider(request):
    # Flag for the template
    registered = False
    
    # If the request method is POST,
    # fetch the data from the user and provider form
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        provider_form = ServiceProvidersForm(data=request.POST)

        if user_form.is_valid() and provider_form.is_valid():
            # Create user
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            # Create provider and associate with user
            provider = provider_form.save(commit=False)
            provider.user = user
            provider.save()
            registered = True
            
            # Log the new user in
            login(request, user)
            
            # Since there are two different types of users,
            # the default registration-redux registration view cannot be used
            # and the user needs to be redirected to the home page manually.            
            # Redirect user to homepage
            return render(request, 'mainUI/index.html')

        else:
            print(user_form.errors, provider_form.errors)
    
    # If it's a GET request, provide user with forms to be filled
    else: 
        user_form = UserForm()
        provider_form = ServiceProvidersForm()

    return render(request, 'registration/provider_registration_form.html', {'user_form': user_form,
                                                                            'provider_form': provider_form,
                                                                            'registered': registered})


# View that allows new customers to register
def register_customer(request):

    # Flag for the template
    registered = False
    
    # If the request method is POST,
    # fetch the data from the user and provider form
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        customer_form = CustomerForm(data=request.POST)

        if user_form.is_valid() and customer_form.is_valid():
            # Create user
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            # Create customer and associate with user
            customer = customer_form.save(commit=False)
            customer.user = user
            customer.save()

            # Log the new user in
            login(request, user)
            registered = True

            # Since there are two different types of users,
            # the default registration-redux registration view cannot be used
            # and the user needs to be redirected to the net page manually.            
            # Redirect user to homepage
            return render(request, 'mainUI/index.html')

        else:
            print(user_form.errors, customer_form.errors)
    
    # If it's a GET request, provide user with forms to be filled
    else: 
        user_form = UserForm()
        customer_form = CustomerForm()

    return render(request, 'registration/customer_registration_form.html', {'user_form': user_form,
                                                                            'customer_form': customer_form,
                                                                            'registered': registered})
 

# View that allows users to see their profiles
@login_required
def user_profile(request):
    
    # Extract the user from the request 
    try:
        user = User.objects.get(username=request.user.username)
    except User.DoesNotExist:
        return render(request, 'mainUI/index.html')
    
    # Determine whether the user is a service provider or a customer
    # Try to relate the User to a ServiceProviders instance.
    # If there is a ServiceProviders instance, it is a service provider, else
    # it is a customer.
    try:
        # Provider variable to be used in the html context
        provider = ServiceProviders.objects.get(user=user)
        context = {
            'user': user,
            'provider': provider    
        }

        # If it is a service provider, show the corresponding profile page
        return render(request, 'mainUI/provider_profile.html', context)
    
    # If the user is a customer
    except ServiceProviders.DoesNotExist:
        # Customer variable to be used in the html context        
        customer = Customer.objects.get(user=user)

        context = {
            'user': user,
            'customer': customer,
            
        }

        # If it is a customer, show the corresponding profile page
        return render(request, 'mainUI/customer_profile.html', context)


# View that allows users to see their pending booking requests
@login_required
def pending_bookings(request):

    try:
        user = User.objects.get(username=request.user.username)
    except User.DoesNotExist:
        return render(request, 'mainUI/index.html')
    
    # Determine whether the user is a service provider or a customer
    # Try to relate the User to a ServiceProviders instance.
    # If there is a ServiceProviders instance, it is a service provider, else
    # it is a customer.
    try:
        # Provider variable to be used in the html context
        provider = ServiceProviders.objects.get(user=user)

        # Create a table that contains the provider's pending booking requests
        table = ProviderPendingBookingsTable(
            Booking.objects.filter(booking_provider=provider,  booking_confirmed=0, booking_canceled=0,
                                   booking_date__gte=datetime.strftime(datetime.now(),
                                                                       '%Y-%m-%d %H:%M:%S')).order_by('booking_date'))
        table.paginate(page=request.GET.get('page', 1), per_page=15)
        
        context = {
            'provider': provider,
            'table': table,
        }

    # If the user is a customer
    except ServiceProviders.DoesNotExist:
        # Customer variable to be used in the html context 
        customer = Customer.objects.get(user=user)
        
        # Create a table that contains the provider's pending booking requests
        table = CustomerPendingBookingsTable(
            Booking.objects.filter(booking_customer=customer, booking_confirmed=0, booking_canceled=0,
                                   booking_date__gte=datetime.strftime(datetime.now(), '%Y-%m-%d %H:%M:%S'))
            .order_by('booking_date'))
        table.paginate(page=request.GET.get('page', 1), per_page=15)
        
        context = {
            'customer': customer,
            'table': table,
        }

    return render(request, 'mainUI/pending_bookings.html', context)


# View that allows users to see their upcoming bookings
@login_required
def upcoming_bookings(request):
    try:
        user = User.objects.get(username=request.user.username)
    except User.DoesNotExist:
        return render(request, 'mainUI/index.html')
 
    # Determine whether the user is a service provider or a customer
    # Try to relate the User to a ServiceProviders instance.
    # If there is a ServiceProviders instance, it is a service provider, else
    # it is a customer.
    try:
        # Provider variable to be used in the html context
        provider = ServiceProviders.objects.get(user=user)
        
        # Create a table that contains the provider's upcoming bookings
        table = ProviderUpcomingBookingsTable(
            Booking.objects.filter(booking_provider=provider,
                                   booking_confirmed=1,
                                   booking_canceled=0,
                                   booking_date__gte=datetime.strftime(datetime.now(), '%Y-%m-%d %H:%M:%S'))
            .order_by('booking_date'))
        table.paginate(page=request.GET.get('page', 1), per_page=15)
        
        context = {
            'provider': provider,
            'table': table,
        }

    # If the user is a customer
    except ServiceProviders.DoesNotExist:
        # Customer variable to be used in the html context
        customer = Customer.objects.get(user=user)
        
        # Create a table that contains the customer's upcoming bookings
        table = CustomerUpcomingBookingsTable(
            Booking.objects.filter(booking_customer=customer,
                                   booking_confirmed=1,
                                   booking_canceled=0,
                                   booking_date__gte=datetime.strftime(datetime.now(), '%Y-%m-%d %H:%M:%S'))
            .order_by('booking_date'))
        table.paginate(page=request.GET.get('page', 1), per_page=15)
        
        context = {
            'customer': customer,

templates/mainUI/about.html
{% extends 'mainUI/tpl_availablesrv.html' %}
{% load staticfiles %}

{% block image %}

    <img src="/static/images/about.jpg" alt="" />

{% endblock %}

{% block title_block %}
{% endblock %}

{% block available_services %}
    
    <div>
    <br><br>
    <h2>What is bookIT?</h2>
        <strong>The goal of bookIT</strong> is to provide a common place for hired services and 
        facilitate the procedure of making a booking. </br></br>If you are a <strong>customer</strong>, <a href="{% url 'mainUI:register_customer' %}">join bookIT</a> and 
        discover how you can enjoy services in a heartbeat! </br>bookIT with us and find out about the 
        amazing services that our trusted providers can offer for you!</br></br>
        If you are a <strong>service provider</strong>, see your appointments skyrocket! </br> 
        <a href="{% url 'mainUI:register_provider' %}">Join bookIT</a> and access
        thousands of customers! Be a part of bookIT and discover all the ways that bookIT can help your business take off!

    </div>
    <br><br><br><br>
    <div>
    <p>
	<a href="/mainUI/" class="button"> Home</a>

    </p>
    </div>
{% endblock %}

templates/mainUI/availablesrv.html
{% extends 'mainUI/tpl_availablesrv.html' %} 

{% block image %}

    <img src="/static/images/select.jpg" alt="" />

{% endblock %}

{% block available_services %}
<ul>
	{% if services %} 
	
	{% for srv in services %}
	<li class="collection-item">
		<h4>
			<a href="/mainUI/srvproviders/{{srv.id}}"> {{srv.service_name}}</a>
		</h4>
	</li>
	{% endfor %} 
	
	{% else %}
	<li class="collection-item">
		<h4>There are currently no services available!</h4>
	</li>
	{% endif %}
</ul>
{%endblock%} 



{% block asbuttons %}
<p>
	<a href="/mainUI/srvgroups/" class="button"> &lt; Back</a>

</p>
{% endblock%}

templates/mainUI/btnConfirm.html
<a href="/mainUI/confirm_booking/{{record.pk}}"> <img src="/static/images/confirm_btn.png" alt=""></a>

templates/mainUI/confirmation.html
{% extends 'mainUI/tpl_availablesrv.html' %}

{% block image %}

    <img src="/static/images/tick.jpg" alt="" />

{% endblock %}

{% block available_services %}


<div class="align-center">
	<h1>Great!</h1>
	<h4>The date you have selected is available!</h4>
	</br></br>
	<a href="/mainUI/request_booking" class="button" style="width:50%">  bookIT! </a>
</div>

{% endblock %}


{% block asbuttons %}
<p>
	<a href="/mainUI/{{ selected_service }}" class="button"> Home</a> 
	

</p>
{% endblock%}

templates/mainUI/index.html
{% extends 'mainUI/layout.html' %}
{% load staticfiles %}

{% block title_block %}
    Index
{% endblock %}

{% block body_block %}
    <br/><br/>
    <h1>Welcome to the simplest homepage!</h1>
{% endblock %}

templates/mainUI/layout.html
<!DOCTYPE HTML>
<!--
	Urban by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html lang="en">
	<head>
		<title>book IT</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="/static/assets/css/main.css" />
		{%block meta%}
		{%endblock%}
	</head>
	<body>

		<!-- Header -->
			<header id="header" class="alt">
				<div class="logo"><a href="/">bookIT <span>by CDrits</span></a></div>
				<a href="#menu">Menu</a>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="/">Home</a></li>
					<li><a href="/mainUI/srvgroups/">Available Services</a></li>					
					{% if user.is_authenticated %}
						<li><a href="{% url 'mainUI:user_profile' %}"> My bookIT: {{user.first_name}}</a></li>
						<li><a href="{% url 'auth_logout' %}?next=/mainUI/">Logout</li>
					{% else %}
						<li><a href="{% url 'auth_login' %}"> Login</a></li>
						<li><a href="{% url 'mainUI:register_customer' %}">Register</a></li>
					{% endif %}					
				</ul>
			</nav>

		<!-- Banner -->
			<section id="banner">
				<div class="inner">
					<header>
						<h1>This is bookIT</h1>
						<p>Todays life is fast!<br/>Book any service you wish in a heartbeat!<br />Fast. Easy. Secure.</p>
					</header>
					<a href="#main" class="button big scrolly">Learn More</a>
				</div>
			</section>

		<!-- Main -->
			<div id="main">

				<!-- Section -->
					<section class="wrapper style1">
						<div class="inner">
							<!-- 2 Columns -->
								<div class="flex flex-2">
									<div class="col col1">
										<div class="image round fit">
											<a href="#" class="link"><img src="/static/images/pic07.jpg" alt="" /></a>
										</div>
									</div>
									<div class="col col2">
										<h3>What is bookIT?</h3>
										<p>bookIT comes to close the gap between today's people needs for services and startup companies that can provide the best quality of service and prices.</p>
										<h3>What bookIT does for you</h3>
										<p>Browse through numerous service categories!<br/> Select the service you wish to enjoy! <br/>See the providers ...... and bookIT!</p>
										<a href="{% url 'mainUI:about' %}" class="button">Learn More</a>   <a href="/mainUI/srvgroups/" class="button">See Available Services</a>
									</div>
								</div>
						</div>
					</section>

				<!-- Section -->
					<section class="wrapper style2">
						<div class="inner">
							<div class="flex flex-2">
								<div class="col col2">
									<h3>Be a part of bookIT</h3>
									<p>Join us to book the services you wish! Easy. Fast. Secure.</p>
									<p> </p>
									<a href="{% url 'mainUI:register_customer' %}" class="button">Join Us Today!</a>
								</div>
								<div class="col col1 first">
									<div class="image round fit">
										<a href="#" class="link"><img src="/static/images/joinus.jpg" alt="" /></a>
									</div>
								</div>
							</div>
						</div>
					</section>

				<!-- Section -->
					<section class="wrapper style1">
						<div class="inner">
							<header class="align-center">
								<h2>Success stories</h2>
								<p>Find out more about how bookIT can help you grow and make your life easier! </p>
							</header>
							<div class="flex flex-3">
								<div class="col align-center">
									<div class="image round fit">
										<img src="/static/images/spa.jpg" alt="" />
									</div>
									<p><strong>Nick, Spa &amp Beauty Studio</strong><br/>“Picking phone calls when having a costumer in is a nightmare. </br>bookIT allows me to manage my bookings when I am not busy! I am no more losing clients because I can't pick up my phone! </p>
									<a href="/mainUI/success_stories/0" class="button">Learn More</a>
								</div>
								<div class="col align-center">
									<div class="image round fit">
										<img src="/static/images/pic05.jpg" alt="" />
									</div>
									<p><strong>Vera, Vera Nails</strong> <br/>“bookIT makes everything simple. Every time a booking is made, all I need is to click a button to confirm it. It is simple and fast! My customers love it as well!</br>Thank you bookIT!"
 									</p>
									<a href="/mainUI/success_stories/1" class="button">Learn More</a>
								</div>
								<div class="col align-center">
									<div class="image round fit">
										<img src="/static/images/pic04.jpg" alt="" />
									</div>
									<p><strong>Emil, student </strong><br/> “bookIT makes booking an appointment a piece of cake! I can search for local services and pick the provider that I like.</br> Being a shy person, I can avoid awkward telephone conversations!”
									</p>
									<a href="/mainUI/success_stories/2" class="button">Learn More</a>
								</div>
							</div>
						</div>
					</section>
					{%block content%}
					{%endblock%}
			</div>

		<!-- Footer -->
			<footer id="footer">
				<div class="copyright">
					<ul class="icons">
						<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="#" class="icon fa-snapchat"><span class="label">Snapchat</span></a></li>
					</ul>
					<p>bookIT by CDrits. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.</p>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="/static/assets/js/jquery.min.js"></script>
			<script src="/static/assets/js/jquery.scrolly.min.js"></script>
			<script src="/static/assets/js/jquery.scrollex.min.js"></script>
			<script src="/static/assets/js/skel.min.js"></script>
			<script src="/static/assets/js/util.js"></script>
			<script src="/static/assets/js/main.js"></script>

	</body>
</html>

templates/mainUI/tpl_availablesrv.html
<!DOCTYPE HTML>

<!--
	Urban by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>

<head>
	<title>book IT</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="stylesheet" href="/static/assets/css/main.css" />

<!-- DateTime links-->
	<link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">

</head>

<body class="subpage">

	<!-- Header -->
	<header id="header">
		<div class="logo">
			<a href="/">book IT
				<span>by CDrits</span>
			</a>
		</div>
		<a href="#menu">Menu</a>
	</header>

	<!-- Nav -->
	<nav id="menu">
		<ul class="links">
			<li>
				<a href="/">Home</a>
			</li>
			<li>
				<a href="/mainUI/srvgroups/">Available Services</a>
			</li>
			{% if user.is_authenticated %}
				<li>
					<a href="{% url 'mainUI:user_profile' %}"> My bookIT: {{user.first_name}}</a>
				</li>
					<li><a href="{% url 'auth_logout' %}?next=/mainUI/">Logout</a>
				</li>
			{% else %}
			<li>
				<a href="{% url 'auth_login' %}"> Login</a>
			</li>
			<li>
				<a href="{% url 'mainUI:register_customer' %}">Register</a>
			</li>
			{% endif %}		
		</ul>
	</nav>

	<!-- Main -->
	<div id="main">

		<!-- Section -->
		<section class="wrapper">
			<div class="inner">
				<header class="align-center">
					<h1>{{title}}</h1>
					<p>{{subtitle}}</p>
				</header>
				<div class="flex flex-2">
					<div class="col col1 first">
						<div class="image round fit">
							<a href="#" class="link">
							{% block image %}
							{% endblock %}
							</a>
						</div>
						
					</div>

					<div class="col col2">
						{% block available_services %}						
						{%endblock%}
					</div>

				</div>
				   {% block asbuttons%}
				   {%endblock%}	
			</div>

		</section>

		
	</div>

	<!-- Footer -->
	<footer id="footer">
		<div class="copyright">
			<ul class="icons">
				<li>
					<a href="#" class="icon fa-twitter">
						<span class="label">Twitter</span>
					</a>
				</li>
				<li>
					<a href="#" class="icon fa-facebook">
						<span class="label">Facebook</span>
					</a>
				</li>
				<li>
					<a href="#" class="icon fa-instagram">
						<span class="label">Instagram</span>
					</a>
				</li>
				<li>
					<a href="#" class="icon fa-snapchat">
						<span class="label">Snapchat</span>
					</a>
				</li>
			</ul>
			<p>&copy; Untitled. All rights reserved. Design:
				<a href="https://templated.co">TEMPLATED</a>. Images:
				<a href="https://unsplash.com">Unsplash</a>.</p>
		</div>
	</footer>

	<!-- Scripts -->
	<script src="/static/assets/js/jquery.min.js"></script>
	<script src="/static/assets/js/jquery.scrolly.min.js"></script>
	<script src="/static/assets/js/jquery.scrollex.min.js"></script>
	<script src="/static/assets/js/skel.min.js"></script>
	<script src="/static/assets/js/util.js"></script>
	<script src="/static/assets/js/main.js"></script>

	<!-- DateTime script -->
	<script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
	
	<script>
		$(function () {
			$('.datetime-input').datetimepicker({
				format:'YYYY-MM-DD HH:mm'
			});
		});
	</script>

</body>

</html>